//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 Plugin.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PLUGIN_FORM                 101
#define IDD_AUTOVIEW                    102
#define IDD_TOPVIEW                     103
#define IDD_BOTTOMVIEW                  104
#define IDD_MANUALVIEW                  105
#define IDD_PRODUCTIONVIEW              106
#define IDD_CONFIGVIEW                  108
#define IDR_MAINFRAME                   128
#define IDD_DLG_MOTOR_CONFIG            129
#define IDR_PluginTYPE                  130
#define IDD_DLG_LIB                     310
#define IDD_DLG_TIMER                   313
#define IDR_MENU1                       313
#define IDR_MENU_RECIPE                 313
#define IDD_DLG_VALVE                   314
#define IDD_DLG_ERROR                   315
#define IDI_ICON_HOME                   318
#define IDI_ICON_EMGSTOP                319
#define IDI_ICON_ALARM                  320
#define IDI_ICON_INFO                   321
#define IDI_ICON_GOFF                   325
#define IDI_ICON_GON                    326
#define IDD_DIALOG_ESTOP                329
#define IDD_DLG_MOTOR                   330
#define IDD_DLG_IO                      331
#define IDD_RECIPEVIEW                  332
#define IDD_DLG_RECIPE                  333
#define IDD_DLG_PILOT                   334
#define IDD_VISIONVIEW                  335
#define IDD_DLG_VISION                  336
#define IDD_DLG_RECIPE_PPARM            337
#define IDD_DLG_COMPONENT               338
#define IDD_DLG_PCB                     339
#define IDC_STATIC_DESCRIPT             1000
#define IDC_BT_AUTO                     1000
#define IDC_CMB_TYPE                    1000
#define IDC_COMBO_SOLUTIONS             1001
#define IDC_TABCONFIG                   1001
#define IDC_BT_PRODUCTION               1001
#define IDC_CMB_FEEDER                  1001
#define IDC_LIST_COMPONENTS             1001
#define IDC_STATIC_MEMO                 1002
#define IDC_BT_MANUAL                   1002
#define IDC_EDIT_ID                     1002
#define IDC_STATIC_HAPPENER             1003
#define IDC_BT_RECIPE                   1003
#define IDC_EDIT_NAME                   1003
#define IDC_BT_CONFIG                   1004
#define IDC_EDIT_HIGH                   1004
#define IDC_BT_STOP                     1005
#define IDC_BTN_ADD                     1005
#define IDC_BT_VISION                   1006
#define IDC_BTN_DEL                     1006
#define IDC_LIST1                       1006
#define IDC_BTN_CANCEL                  1007
#define IDC_EDIT_SEARCH                 1007
#define IDC_BTN_SEARCH                  1008
#define IDC_COMBO1                      1009
#define IDC_BTN_YP                      1010
#define IDC_BTN_YM                      1011
#define IDC_BTN_XP                      1012
#define IDC_PICTURE_AUTO                1012
#define IDC_BTN_XM                      1013
#define IDC_BTN_START                   1013
#define IDC_BTN_PITCH4                  1014
#define IDC_STATIC_PCBPICT              1014
#define IDC_BTN_RMOVEP                  1015
#define IDC_BTN_ZP                      1015
#define IDC_EDIT_MARK_X1                1015
#define IDC_BTN_PITCH3                  1016
#define IDC_EDIT_MARK_X2                1016
#define IDC_BTN_PITCH2                  1017
#define IDC_EDIT_MARK_X3                1017
#define IDC_BTN_HOME                    1018
#define IDC_BTN_ZM                      1018
#define IDC_EDIT_MARK_X4                1018
#define IDC_STC_SPEED                   1019
#define IDC_BTN_RM                      1019
#define IDC_EDIT_MARK_Y1                1019
#define IDC_STC_LAST                    1020
#define IDC_BTN_RP                      1020
#define IDC_EDIT_MARK_Y2                1020
#define IDC_STC_POS                     1021
#define IDC_EDIT_MARK_Y3                1021
#define IDC_BTN_STOP                    1022
#define IDC_EDIT_MARK_Y4                1022
#define IDC_LIST_MOTORS                 1023
#define IDC_EDIT_BASE_X                 1023
#define IDC_EDIT_P1                     1024
#define IDC_LIST_MOTORS2                1024
#define IDC_EDIT_BASE_Y                 1024
#define IDC_LIST_MSG                    1025
#define IDC_EDIT_P2                     1025
#define IDC_CMB_NX                      1025
#define IDC_STATIC_LOGO                 1026
#define IDC_BTN_TEST                    1026
#define IDC_CMB_NY                      1026
#define IDC_BTN_RMOVEM                  1027
#define IDC_STATIC_HAPPENER_CAP         1027
#define IDC_EDIT_PITCH_X                1027
#define IDC_BTN_STATUS                  1027
#define IDC_BTN_PITCH1                  1028
#define IDC_STATIC_DESCRIPT_CAP         1028
#define IDC_EDIT_PITCH_Y                1028
#define IDC_BTN_PITCH0                  1029
#define IDC_STATIC_MEMO_CAP             1029
#define IDC_EDIT_BASE_Z                 1029
#define IDC_BTN_PITCH5                  1030
#define IDC_STATIC_SOLUTION_CAP         1030
#define IDC_BTN_SAVE                    1031
#define IDC_STATIC_EMGSTOP              1031
#define IDC_BTN_P1                      1032
#define IDC_BTN_P2                      1033
#define IDC_BTN_OPEN                    1034
#define IDC_EDIT_HISPEED                1034
#define IDC_CMB_PLSMODE                 1034
#define IDC_LIST_VALVES                 1035
#define IDC_EDIT_LOSPEED                1035
#define IDC_CMB_FEEDBACK                1035
#define IDC_BTN_CLOSE                   1036
#define IDC_EDIT_HIACCTIME              1036
#define IDC_CMB_ENCODER                 1036
#define IDC_BTN_REPEAT                  1037
#define IDC_LIST_TIMERS                 1037
#define IDC_EDIT_HIDESTIME              1037
#define IDC_CMB_INPL                    1037
#define IDC_EDIT                        1038
#define IDC_EDIT_LOACCTIME              1038
#define IDC_CMB_MINP                    1038
#define IDC_EDIT_LODESTIME              1039
#define IDC_LIST_IO_X                   1039
#define IDC_CMB_ENCL                    1039
#define IDC_TAB_RECIPE                  1040
#define IDC_LIST_IO_Y                   1040
#define IDC_LED1                        1040
#define IDC_LIST_RECIPES                1041
#define IDC_TAB_DISPLAY                 1041
#define IDC_LED2                        1041
#define IDC_CMB_ALML                    1041
#define IDC_CMB_SV                      1042
#define IDC_LIST_FEEDER                 1042
#define IDC_STC_X_POS                   1042
#define IDC_LED3                        1042
#define IDC_CMB_ALMM                    1042
#define IDC_TAB_VISION                  1043
#define IDC_CMB_BUZZ                    1043
#define IDC_STC_Y_POS                   1043
#define IDC_LED4                        1043
#define IDC_CMB_ELL                     1043
#define IDC_STC_Z1                      1044
#define IDC_LED5                        1044
#define IDC_CMB_LTCSD                   1044
#define IDC_STC_R1                      1045
#define IDC_LED6                        1045
#define IDC_CMB_LTCL                    1045
#define IDC_STC_Z2                      1046
#define IDC_LED7                        1046
#define IDC_CMB_SDL                     1046
#define IDC_STC_R2                      1047
#define IDC_LED8                        1047
#define IDC_CMB_SDM                     1047
#define IDC_STC_Z3                      1048
#define IDC_LED9                        1048
#define IDC_CMB_ORGL                    1048
#define IDC_STC_R3                      1049
#define IDC_LED10                       1049
#define IDC_STC_Z4                      1050
#define IDC_LED11                       1050
#define IDC_CMB_SVL                     1050
#define IDC_STC_R4                      1051
#define IDC_LED12                       1051
#define IDC_CMB_EZL                     1051
#define IDC_STC_Z5                      1052
#define IDC_BTN_CONFIG                  1052
#define IDC_STC_R5                      1053
#define IDC_STC_Z6                      1054
#define IDC_LED13                       1054
#define IDC_STC_R6                      1055
#define IDC_LED14                       1055
#define IDC_LED15                       1056
#define IDC_TREE_SYSTEM                 1349
#define IDD_DLG_SYSTEM_STATUS           11170
#define IDD_DLG_AUTO_MOTORS             11171
#define ID_32771                        32771
#define ID_Menu                         32772
#define ID_32773                        32773
#define ID_RECIPE_INSERT                32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        314
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
